export type ObjectOptionsContentId =
  | 'layout'
  | 'layoutOpenIn'
  | 'fields'
  | 'hiddenFields'
  | 'recordGroups'
  | 'hiddenRecordGroups'
  | 'recordGroupFields'
  | 'recordGroupSort'
  | 'calendarFields'
  | 'calendarView'
  | 'roadmapStartField'
  | 'roadmapEndField'
  | 'roadmapColorField'
  | 'visibility';
